module.exports = {
    ARBITRUM_MAINNET: {
        chainId: 42161,
        nativeAsset: 'ETH',
        bundlerUrl: process.env.REACT_APP_BUNDLER_ARBITRUM_MAINNET,
        paymasterUrl: process.env.REACT_APP_PAYMASTER_ARBITRUM_MAINNET,
        rpcUrl: 'https://rpc.ankr.com/arbitrum',
        networkName: 'Arbitrum Mainnet (42161)',
        name: 'ARBITRUM_MAINNET',
        wrappedAsset: 'WETH',
        wrappedAssetAddress: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    },
    ARBITRUM_TESTNET: {
        chainId: 421613,
        nativeAsset: 'tETH',
        bundlerUrl: process.env.REACT_APP_BUNDLER_ARBITRUM_TESTNET,
        paymasterUrl: process.env.REACT_APP_PAYMASTER_ARBITRUM_TESTNET,
        rpcUrl: 'https://arbitrum-goerli.publicnode.com',
        networkName: 'Arbitrum Testnet (421613)',
        name: 'ARBITRUM_TESTNET',
        wrappedAsset: 'WETH',
        wrappedAssetAddress: '0xe39Ab88f8A4777030A534146A9Ca3B52bd5D43A3',
    },
    POLYGON_MAINNET: {
        chainId: 137,
        nativeAsset: 'MATIC',
        bundlerUrl: process.env.REACT_APP_BUNDLER_POLYGON,
        paymasterUrl: process.env.REACT_APP_PAYMASTER_POLYGON,
        rpcUrl: 'https://rpc.ankr.com/polygon',
        networkName: 'Polygon Mainnet (137)',
        name: 'POLYGON_MAINNET',
        wrappedAsset: 'WMATIC',
        wrappedAssetAddress: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
    },
    POLYGON_MUMBAI: {
        chainId: 80001,
        nativeAsset: 'tMATIC',
        bundlerUrl: process.env.REACT_APP_BUNDLER_MUMBAI,
        paymasterUrl: process.env.REACT_APP_PAYMASTER_MUMBAI,
        rpcUrl: 'https://rpc.ankr.com/polygon_mumbai',
        networkName: 'Polygon Mumbai (80001)',
        name: 'POLYGON_MUMBAI',
        wrappedAsset: 'WMATIC',
        wrappedAssetAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
    },
    BSC_MAINNET: {
        chainId: 56,
        nativeAsset: 'BNB',
        bundlerUrl: process.env.REACT_APP_BUNDLER_BSC_MAINNET,
        paymasterUrl: process.env.REACT_APP_PAYMASTER_BSC_MAINNET,
        rpcUrl: 'https://rpc.ankr.com/bsc',
        networkName: 'BSC Mainnet (56)',
        name: 'BSC_MAINNET',
        wrappedAsset: 'WBNB',
        wrappedAssetAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    },
    BSC_TESTNET: {
        chainId: 97,
        nativeAsset: 'tBNB',
        bundlerUrl: process.env.REACT_APP_BUNDLER_BSC_TESTNET,
        paymasterUrl: process.env.REACT_APP_PAYMASTER_BSC_TESTNET,
        rpcUrl: 'https://rpc.ankr.com/bsc_testnet_chapel',
        networkName: 'BSC Testnet (97)',
        name: 'BSC_TESTNET',
        wrappedAsset: 'WBNB',
        wrappedAssetAddress: '0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd',
    }
}